language: go
go:
- 1.6
- 1.5
- 1.4
- 1.3
- 1.2
env: CHESSBASEURL="http://localhost:8082/"
addons:
  mariadb: '5.5'
matrix:
 allow_failures:
  - go: 1.3
        # include:
        #  - go: 1.6
        #    env: TESTUJEMY_MARIADB=10.1 CHESSBASEURL="http://localhost:8082/"
        #    addons:
        #      mariadb: '10.1'
before_install:
- mysqladmin variables | grep socket
- sudo mkdir /var/run/mysql
- sudo ln -s /var/run/mysqld/mysqld.sock /var/run/mysql/mysql.sock
- echo "" > coverage.txt
- go get github.com/onsi/gomega
- go get github.com/onsi/ginkgo
- go get golang.org/x/tools/cmd/cover
- go get github.com/go-sql-driver/mysql
- go get github.com/gorilla/mux
- go get github.com/dghubble/sling
- go get github.com/coreos/pkg/flagutil
install:
- ln -s $PWD $GOPATH/src/github.com/ArchieT/3manchess
- sh -c "mysql -e 'create database if not exists archiet;'; mysql archiet < $GOPATH/src/github.com/ArchieT/3manchess/server/mojsql/setup.sql"
- go install -v -race github.com/ArchieT/3manchess/movedet
- go install -v -race github.com/ArchieT/3manchess/player
- go install -v -race github.com/ArchieT/3manchess/interface/devengfmt
- go install -v -race github.com/ArchieT/3manchess/cmd/3manchess-devengfmt
- go install -v -race github.com/ArchieT/3manchess/cmd/3manchess-devengchan
- go install -v -race github.com/ArchieT/3manchess/ai/constsitval
- go install -v -race github.com/ArchieT/3manchess/ai/sitvalues
- go install -v -race github.com/ArchieT/3manchess/interface/gui
- go install -v -race github.com/ArchieT/3manchess/server
- go install -v -race github.com/ArchieT/3manchess/server/mojsql
- go install -v -race github.com/ArchieT/3manchess/multi
- go install -v -race github.com/ArchieT/3manchess/cmd/trychessserver
- go install -v -race github.com/ArchieT/3manchess/client
- go install -v -race github.com/ArchieT/3manchess/client/remote
- go install -v -race github.com/ArchieT/3manchess/cmd/chessrunbot
script:
- (while true; do echo "while - trychessserver starting again"; trychessserver -d archiet -u root; done) &
- go test github.com/ArchieT/3manchess/game -covermode=atomic -coverprofile=tmpgame.out
- cat tmpgame.out >> coverage.txt
- go test github.com/ArchieT/3manchess/movedet -covermode=atomic -coverprofile=tmpmovedet.out
- cat tmpmovedet.out >> coverage.txt
- go test -v github.com/ArchieT/3manchess/ai/constsitval -covermode=atomic -coverprofile=tmpconsv.out
- cat tmpconsv.out >> coverage.txt
- go test -v github.com/ArchieT/3manchess/server/mojsql -covermode=atomic -coverprofile=tmpmojsql.out
- cat tmpmojsql.out >> coverage.txt
- go test -v github.com/ArchieT/3manchess/client/remote -covermode=atomic -coverprofile=tmprem1.out
  -timeout=1m || true
- cat tmprem1.out >> coverage.txt || true
- go test -v github.com/ArchieT/3manchess/client/remote -covermode=atomic -coverprofile=tmprem2.out
  -timeout=1m || true
- cat tmprem2.out >> coverage.txt || true
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  slack:
          rooms:
                  - secure: KGLUOXcJny4R8yfUkX13A+xTjxuhOPtGYYsQm3am7Lr1UsAeYDKNmFt1H4ErPyIW8ZHB8TICGB2TnjqH3qRy4VsF+iblhWONJkeK8UCSkiltTj+px36YfdPUyWxHFKji/nt6uzKriUcbtKXKrLaSt31Wsm7IlwSFW7DkfHIlgJvTCrXR+FNQkVajQ4RjIvqD/9QevYaJo1+jn3N8y+NJWAshzw06pZl58xYu9oqksF/ft34iKvrhcpDpyLA09htWVJaNBzozY/1Pvh+xIQ3SjbFFspBFu+o9cOLZOxmbofYjsJOTaKjP9Ros7JrYR2j7ZOWni+hitGLj+ru8/mwTIvZlqFOriWSHtw5jtvkHLd2r6pfCV+Wu8GAcsRO+9v4zjZDBG0R8FD71YADwqxqytF++L38fU0lrhKXL2WcNLUYkDMr+XuzORkOeajtvy7D9cyrLuPzS/O6YxpxOJaciNgAAkYT/+bvN8WvEeHkTt+YwJrVG98aV2Vy6vk9jwIUSBDJ4T46WuMkHPiav3kI8qSNOpHFCNLtBMqixZXutwYnvBj7IcMIlvQDh9hZ2e8H0ZI8yRmhNQ0RG8vRF+NR5dcEVlLPzD/5bDpSyy5oCzoN0kMEAerY/DQfmpB6nYrIHF286IiAl0JmbUnpaD6XCrsJO5xZMUI319VgQlCIeaU4=
                    on_success: never
                    on_failure: always
                  - secure: igB8y+vprHoTX+JA9Phf3caJRJg/81wiRgcHbaC6OKUlsushz89IbzE3WAWbhJPDlAwR8pcLKbC3CKvJ0BABedZAdmssF0sMX8NeKbeWPTDPzIHCKxcSsaBAzr0lnTTyU6uajd0HsXliidUUP1wfWE8J/SvdShI3BOcd8+F6/YiIqmqwSA5mYjapD+XKKwu4SiZGhic2UHBHB+n1xHk9MSpUq1clNk+19uG2sZG+tMjFEDKmyhZCBEa1jzYBzbW7Ka5RI4et8ua70I3w8W/PKI5nrYAcEIkpBZZpzNRZNN+Koo+vPfN6FHQGbQhPHSxsqsji0/iB3hDAB2Et5KeDFDHUK+XBNBLXUNs+2ZhFndVDvMCfMI2W7YuwYlydes73Si3EZyQhewPvxwNJBWVvWRChbGAOo8iDyFYhCVaOcAIE1HcKuFp2dC3hIjbZKsaKhGFpXyC++rKDTzyHQ46EsBXvV0oi6NToiNWnTUwwW10fwXnRteU/XJ3YikS5LY2fnTuGr218jXZlIuUgpa55jFSnFf4omgFSjrAzNKoe+fNXOnU3d8DEn3zOcI87LJBN7U2yY6Y+pBQH9HIK+Bx0XxDqlkXQIZ5a/KpqAZoKtRmazTgbVBfKxdmC/UEgyfS9ZqhrbXbxnwsTbPkKJza3K/OlXyfL9A/oN6wVbxhCaPw=
                    on_success: always
                    on_failure: always
                    on_start: always
  email:
          recipients:
                  - archiet@platinum.edu.pl
          on_pull_requests: true
